openapi: 3.0.3
info:
  title: Calculator
  description: |-
    Simple calculator test with additions and subtractions 
  version: 1.0-SNAPSHOT
servers:
  - url: http://localhost:8080
tags:
  - name: operations
    description: operations performed by the calculator
paths:
  /calculator:
    post:
      tags:
        - operations
      summary: performs the operations of a calculator
      description: performs the operations of a calculator
      operationId: calculator
      requestBody:
        description: two numbers and the operator of the operation to be performed
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CalculatorInput'
        required: true
      responses:
        204:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Result'
  /calculator/availableOperations:
    get:
      tags:
        - availableOperations
      summary: operations available
      description: operations available on the calculator
      operationId: operations
      responses:
        204:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AvailableOperations'
components:
  schemas:
    CalculatorInput:
      type: object
      properties:
        firstOperator:
          type: number
        secondOperator:
          type: number
        operation:
          type: string
    Result:
      type: object
      properties:
        result:
          type: number
    AvailableOperations:
      type: object
      properties:
        availableOperations:
          type: array
          items:
            type: string
    BadRequestError:
      type: object
      properties:
        message:
          type: string
