openapi: 3.0.3
info:
  title: Calculator
  description: |-
    Simple calculator test with additions and subtractions 
  version: 1.0-SNAPSHOT
servers:
  - url: http://calculator/api/v1
tags:
  - name: operations
    description: operations performed by the calculator
paths:
  /operations/sum:
    post:
      tags:
        - operations
      summary: Performs the sum operation
      description: Performs the sum of two numbers
      operationId: sum
      requestBody:
        description: Two numbers to add
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Operators'
        required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: number
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
  /operations/subtraction:
    post:
      tags:
        - operations
      summary: Performs the subtraction operation
      description: Performs the subtraction of two numbers
      operationId: subtraction
      requestBody:
        description: Two numbers to add
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Operators'
        required: true
      responses:
        204:
          description: Success
          content:
            application/json:
              schema:
                type: number          
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
components:
  schemas:
    Operators:
      type: object
      properties:
        firstOperator:
          type: number
        SecondOperator:
          type: number
    BadRequestError:
      type: object
      properties:
        message:
          type: string
